-- Create the songs table if it doesn't exist
CREATE TABLE IF NOT EXISTS catholic_songs (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    composer VARCHAR(255),
    language VARCHAR(50),
    theme VARCHAR(255),
    mass_part VARCHAR(255)
);

-- Clear existing data (optional, but good for clean seeding)
TRUNCATE TABLE catholic_songs RESTART IDENTITY;

-- Insert English Catholic Songs
INSERT INTO catholic_songs (title, composer, language, theme, mass_part) VALUES 
('Here I Am, Lord', 'Dan Schutte', 'English', 'Vocation, Discipleship, Trust', 'Entrance, Offertory'),
('Be Not Afraid', 'Bob Dufford', 'English', 'Comfort, Trust, Hope', 'Communion, Recessional'),
('On Eagle''s Wings', 'Michael Joncas', 'English', 'Comfort, Trust, Funeral', 'Communion'),
('City of God', 'Dan Schutte', 'English', 'Light, Discipleship, Mission', 'Entrance, Recessional'),
('Gather Us In', 'Marty Haugen', 'English', 'Gathering, Unity, Welcome', 'Entrance'),
('All Are Welcome', 'Marty Haugen', 'English', 'Unity, Gathering, Diversity', 'Entrance'),
('One Bread, One Body', 'John Foley', 'English', 'Eucharist, Unity', 'Communion'),
('I Am the Bread of Life', 'Suzanne Toolan', 'English', 'Eucharist, Eternal Life', 'Communion'),
('Taste and See', 'James Moore', 'English', 'Eucharist, Goodness, Psalm', 'Communion'),
('The Summons', 'John L. Bell', 'English', 'Vocation, Discipleship, Mission', 'Offertory, Recessional'),
('Blest Are They', 'David Haas', 'English', 'Beatitudes, Comfort', 'Offertory, Communion'),
('Table of Plenty', 'Dan Schutte', 'English', 'Gathering, Eucharist, Welcome', 'Entrance, Offertory'),
('Lead Me, Lord', 'John D. Becker', 'English', 'Guidance, Discipleship', 'Entrance, Communion'),
('Christ, Be Our Light', 'Bernadette Farrell', 'English', 'Light, Hope, Mission, Advent', 'Entrance, Offertory'),
('Lord, You Have Come to the Seashore', 'Cesareo Gabarain', 'English', 'Vocation, Discipleship', 'Offertory, Communion'),
('How Great Thou Art', 'Stuart K. Hine', 'English', 'Praise, Creation', 'Entrance, Recessional'),
('Holy God, We Praise Thy Name', 'Ignaz Franz', 'English', 'Praise, Trinity', 'Entrance, Recessional'),
('Hail Mary: Gentle Woman', 'Carey Landry', 'English', 'Mary, Peace', 'Offertory, Communion'),
('Immaculate Mary', 'Traditional', 'English', 'Mary, Praise', 'Entrance, Recessional'),
('Sing to the Mountains', 'Bob Dufford', 'English', 'Praise, Joy, Easter', 'Entrance, Recessional'),
('Though the Mountains May Fall', 'Dan Schutte', 'English', 'Trust, Faithfulness', 'Offertory, Communion'),
('We Are Called', 'David Haas', 'English', 'Justice, Mission, Discipleship', 'Entrance, Recessional'),
('Canticle of the Sun', 'Marty Haugen', 'English', 'Creation, Praise', 'Entrance, Recessional'),
('Let All Mortal Flesh Keep Silence', 'Traditional', 'English', 'Reverence, Eucharist, Advent', 'Communion'),
('Panis Angelicus', 'Cesar Franck', 'English', 'Eucharist, Adoration', 'Communion'),
('Let There Be Peace on Earth', 'Sy Miller', 'English', 'Peace, Unity', 'Recessional'),
('Joyful, Joyful, We Adore Thee', 'Henry van Dyke', 'English', 'Praise, Joy', 'Entrance, Recessional'),
('Glory and Praise to Our God', 'Dan Schutte', 'English', 'Praise, Thanksgiving', 'Entrance, Recessional'),
('Hosea', 'Gregory Norbet', 'English', 'Repentance, Return, Lent', 'Entrance, Offertory'),
('Lord of the Dance', 'Sydney Carter', 'English', 'Life of Christ, Joy', 'Recessional'),
('Make Me a Channel of Your Peace', 'Sebastian Temple', 'English', 'Peace, Service', 'Offertory, Communion'),
('O God, Our Help in Ages Past', 'Isaac Watts', 'English', 'Trust, Comfort, Funeral', 'Entrance, Recessional'),
('Praise to the Lord, the Almighty', 'Joachim Neander', 'English', 'Praise, Thanksgiving', 'Entrance, Recessional'),
('Seek Ye First', 'Karen Lafferty', 'English', 'Trust, Kingdom of God', 'Offertory, Communion'),
('Take and Eat', 'Michael Joncas', 'English', 'Eucharist, Sacrifice', 'Communion'),
('The Cry of the Poor', 'John Foley', 'English', 'Justice, Psalm, Comfort', 'Offertory, Communion'),
('We Gather Together', 'Traditional', 'English', 'Gathering, Thanksgiving', 'Entrance'),
('We Walk by Faith', 'Marty Haugen', 'English', 'Faith, Trust', 'Offertory, Communion'),
('You Are Mine', 'David Haas', 'English', 'Comfort, Trust, Calling', 'Communion'),
('Your Words Are Spirit and Life', 'Bernadette Farrell', 'English', 'Word of God, Psalm', 'Offertory'),
('Abba, Father', 'Carey Landry', 'English', 'Trust, Petition', 'Offertory, Communion'),
('All Creatures of Our God and King', 'William H. Draper', 'English', 'Praise, Creation', 'Entrance, Recessional'),
('Alleluia! Sing to Jesus', 'William C. Dix', 'English', 'Praise, Easter, Eucharist', 'Entrance, Recessional'),
('As the Deer Longs', 'Bob Hurd', 'English', 'Longing, Psalm', 'Offertory, Communion'),
('Awake! Awake, and Greet the New Morn', 'Marty Haugen', 'English', 'Advent, Joy', 'Entrance'),
('Bread of Life', 'Bernadette Farrell', 'English', 'Eucharist, Unity', 'Communion'),
('Come, Holy Ghost', 'Traditional', 'English', 'Holy Spirit, Pentecost', 'Entrance, Recessional'),
('Crown Him with Many Crowns', 'Matthew Bridges', 'English', 'Christ the King, Praise', 'Entrance, Recessional'),
('Eye Has Not Seen', 'Marty Haugen', 'English', 'Comfort, Heaven, Trust', 'Communion'),
('For All the Saints', 'William W. How', 'English', 'Saints, Eternal Life', 'Entrance, Recessional');

-- Insert Tagalog Catholic Songs
INSERT INTO catholic_songs (title, composer, language, theme, mass_part) VALUES 
('Ama Namin', 'Eduardo Hontiveros', 'Tagalog', 'Lord''s Prayer, Petition', 'Our Father'),
('Pananagutan', 'Eduardo Hontiveros', 'Tagalog', 'Community, Responsibility, Love', 'Entrance, Recessional'),
('Tanging Yaman', 'Manoling Francisco', 'Tagalog', 'Love, Trust, Offering', 'Offertory, Communion'),
('Hindi Kita Malilimutan', 'Manoling Francisco', 'Tagalog', 'Comfort, Trust, Love', 'Communion, Funeral'),
('Sa ''Yo Lamang', 'Manoling Francisco', 'Tagalog', 'Commitment, Love, Offering', 'Offertory, Communion'),
('Anima Christi', 'Jandi Arboleda', 'Tagalog', 'Eucharist, Healing, Soul', 'Communion'),
('Huwag Kang Mangamba', 'Manoling Francisco', 'Tagalog', 'Comfort, Trust', 'Communion'),
('Awit ng Paghahangad', 'Charlie Cenzon', 'Tagalog', 'Longing, Trust, Psalm', 'Offertory, Communion'),
('Likhain Mong Muli', 'Albert Alejo', 'Tagalog', 'Repentance, Renewal, Lent', 'Entrance, Offertory'),
('Papuri sa Diyos', 'Eduardo Hontiveros', 'Tagalog', 'Praise, Glory', 'Gloria'),
('Kordero ng Diyos', 'Eduardo Hontiveros', 'Tagalog', 'Mercy, Peace', 'Lamb of God'),
('Santo', 'Eduardo Hontiveros', 'Tagalog', 'Praise, Holiness', 'Holy'),
('Unang Alay', 'Rey Magnaye', 'Tagalog', 'Offering, Sacrifice', 'Offertory'),
('Pag-aalay ng Puso', 'Nemy Que', 'Tagalog', 'Offering, Love', 'Offertory'),
('Pananalig', 'Silvino Borres Jr.', 'Tagalog', 'Faith, Trust', 'Communion'),
('Hesus ng Aking Buhay', 'Arnel Aquino', 'Tagalog', 'Comfort, Salvation, Jesus', 'Communion'),
('Ito Ang Araw', 'Arnel Aquino', 'Tagalog', 'Joy, Praise, Psalm', 'Entrance, Recessional'),
('Buksan ang Aming Puso', 'Rolando Tinio', 'Tagalog', 'Repentance, Word, Holy Spirit', 'Entrance, Offertory'),
('Halina, Hesus, Halina', 'Eduardo Hontiveros', 'Tagalog', 'Advent, Hope', 'Entrance'),
('Ang Puso Ko''y Nagpupuri', 'Eduardo Hontiveros', 'Tagalog', 'Magnificat, Mary, Praise', 'Recessional'),
('Bayan, Umawit', 'Manoling Francisco', 'Tagalog', 'Praise, Gathering', 'Entrance, Recessional'),
('Panginoon, Maawa Ka', 'Eduardo Hontiveros', 'Tagalog', 'Mercy, Repentance', 'Kyrie'),
('Aleluya', 'Manoling Francisco', 'Tagalog', 'Gospel Acclamation, Joy', 'Alleluia'),
('Dakilang Amen', 'Manoling Francisco', 'Tagalog', 'Praise, Agreement', 'Amen'),
('Ama Namin', 'Manoling Francisco', 'Tagalog', 'Lord''s Prayer, Petition', 'Our Father'),
('Kordero Ng Diyos', 'Manoling Francisco', 'Tagalog', 'Mercy, Peace', 'Lamb of God'),
('Pagsibol', 'Arnel Aquino', 'Tagalog', 'Creation, Growth, Offering', 'Offertory'),
('Paghahandog Ng Sarili', 'Jandi Arboleda', 'Tagalog', 'Offering, Ignatian, Dedication', 'Offertory'),
('Kunin At Tanggapin', 'Manoling Francisco', 'Tagalog', 'Offering, Ignatian', 'Offertory'),
('Tinapay Ng Buhay', 'Manoling Francisco', 'Tagalog', 'Eucharist, Life', 'Communion'),
('Sa Piging Ng Panginoon', 'Bienvenida Tabuena', 'Tagalog', 'Eucharist, Gathering', 'Entrance, Communion'),
('Awit Ng Paglaya', 'Eduardo Hontiveros', 'Tagalog', 'Freedom, Deliverance', 'Recessional'),
('Magnificat', 'Lui Morano', 'Tagalog', 'Mary, Praise', 'Communion, Recessional'),
('Mariang Ina Ko', 'Onofre Pagsanghan', 'Tagalog', 'Mary, Love', 'Communion, Recessional'),
('Stella Maris', 'Silvino Borres Jr.', 'Tagalog', 'Mary, Guidance, Sea', 'Communion, Recessional'),
('Aba Ginoong Maria', 'Manoling Francisco', 'Tagalog', 'Mary, Hail Mary', 'Offertory'),
('O Hesus, Hilumin Mo', 'Manuel Francisco', 'Tagalog', 'Healing, Comfort', 'Communion'),
('Huwag Limutin', 'Arnel Aquino', 'Tagalog', 'Remembrance, Trust', 'Communion'),
('Maging Akin Muli', 'Arnel Aquino', 'Tagalog', 'Return, Love, Forgiveness', 'Communion'),
('Panginoon, Aking Tanglaw', 'Felipe Fruto Ll. Ramirez', 'Tagalog', 'Light, Trust, Psalm 27', 'Communion'),
('Sa Diyos Lamang Mapapanatag', 'Felipe Fruto Ll. Ramirez', 'Tagalog', 'Peace, Trust, Psalm 62', 'Communion'),
('Liwanag Ng Aming Puso', 'Luis Antonio Tagle', 'Tagalog', 'Holy Spirit, Light', 'Entrance, Communion'),
('Manatili Ka', 'Arnel Aquino', 'Tagalog', 'Presence, Comfort', 'Communion'),
('Laging Tapat', 'Noel Miranda', 'Tagalog', 'Faithfulness, Trust', 'Communion'),
('Awit ng Pasasalamat', 'Eduardo Hontiveros', 'Tagalog', 'Thanksgiving, Praise', 'Recessional'),
('Mapapalad', 'Julius Rosales', 'Tagalog', 'Beatitudes, Blessing', 'Offertory, Communion'),
('Salamat Sa Diyos', 'Felipe Fruto Ll. Ramirez', 'Tagalog', 'Thanksgiving', 'Recessional'),
('Humayo''t Ihayag', 'Manoling Francisco', 'Tagalog', 'Mission, Evangelization, Joy', 'Recessional'),
('Panalangin sa Maging Bukas Palad', 'Jandi Arboleda', 'Tagalog', 'Generosity, Ignatian', 'Offertory'),
('Sino Ako', 'Jose Castles', 'Tagalog', 'Humility, Love, Identity', 'Communion');
